# https://stylelint.io/user-guide/configuration/
# https://stylelint.io/user-guide/rules/
# https://stylelint.io/user-guide/faq/#how-do-i-turn-off-disable-or-ignore-a-rule

plugins:
  - "stylelint-scss"
# extends: stylelint-config-recommended-scss

syntax: scss

files:
  - "src/**/*.css"
ignoreFiles:
  - "**/*_"
  - "bundles/"

rules:
  indentation:
    - 2
    -
      severity: warning
  # string-quotes: single
  block-no-empty: null
  no-invalid-double-slash-comments: true
  # rule-empty-line-before: always
  declaration-colon-space-before: never
  declaration-colon-space-after: always
  media-feature-range-operator-space-before: never
  media-feature-range-operator-space-after: always
  media-feature-colon-space-before: never
  media-feature-colon-space-after: always
